### ISSUE TITLE
Idea 

### ISSUE THREAD

**Issue by BugBountyzip** [PortSwigger/bambdas#36]
Dear PortSwigger Team,

I  have successfully secured the Twitter handles @Bambdas and @Bambda_Store. These accounts will serve as valuable resources for sharing our latest Bambda scripts upon their release. Our vision is to create an interactive space where the community can engage in exchanging ideas, showcasing their script creations, and learning from one another.

![image](https://github.com/PortSwigger/bambdas/assets/133497067/d611dd60-ab3d-44b5-9779-d0685794a349)

We believe that this community-focused initiative will greatly enhance the visibility and growth of Burp Suite, particularly in showcasing the versatility and utility of Bambda scripts. I am excited about the potential of these accounts to foster collaboration and innovation within our user base.

Looking forward to your thoughts and support in this endeavor.

Best regards,

**Comment by Hannah-PortSwigger** [comment]
Hi.

Thank you very much for your community contributions - we love the amount of Bambdas you have submitted, and any more that you have would be very welcome.

With regards to Twitter:
Unfortunately, we have no plans to maintain a separate Twitter account for Bambdas. We prefer most of our interactions to be with our official Twitter accounts, through our official GitHub repositories, or other platforms maintained by us.

By all means, feel free to promote Bambdas that you've found interesting or created on your Twitter account. However, we do ask that you make it more obvious that your Twitter accounts are unofficial by not using our branding and logos.

**Comment by BugBountyzip** [comment]
Hello,

You are always welcome.

I have removed the logo, name, and background as requested.
