### ISSUE TITLE
contributor recognition transparency missing from repo

### ISSUE THREAD

**Issue by GangGreenTemperTatum** [PortSwigger/bambdas#75]
hello! this is not a code issue, but i was wondering if the portswigger team would be open to creating a contributions wall ([example](https://github.com/anushka23g/Learning-Made-Easy/issues/16))?

the intent is to showcase contributors in a better light, which is not well apparent from the individual Bambda comments, this also makes it very difficult from a personal standpoint to reference my open-source contributions

example of my prior contributions:

https://github.com/PortSwigger/bambdas/pull/61 -> code [blob](https://github.com/GangGreenTemperTatum/bambdas-fork/blob/0de5cfe1e47dd0870f0ed71ab40fd9dd1159194b/Proxy/HTTP/FilterAuthenticatedNonBearerTokens.bambda) -> [example blob update since the refactor of directory structure in the repo](https://github.com/PortSwigger/bambdas/blob/main/Filter/Proxy/HTTP/FilterAuthenticatedNonBearerTokens.bambda)

tyia!

**Comment by Hannah-PortSwigger** [comment]
Hi

Could you please provide an example of the contributions wall you are looking for, as it seems you've linked an issue that describes the same thing as what you are looking for?

Taking a look at the contributor page under "Insights", it's quite easy to identify people who've contributed to the repository, as well as see a log of the commits that they have contributed. Additionally, you can easily link directly to your accredited file or formatted README copy.

**Comment by Hannah-PortSwigger** [comment]
Hi.

Thank you for your feedback.

Currently, we think the level of accreditation on the repository is sufficient. At the moment, it is easy to see the individual contributions a user has made using GitHub's contribution insights. Additionally, users can use the author tag to further surface their contributions to their Bambdas.

If the repository gets busier, to the point where it is difficult to identify an individual user's contributions, we'll be happy to revisit this idea.

If there's anything else we can help with, then please let us know.
